# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
#- script: echo Hello, world!
#  displayName: 'Run a one-line script'
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'AzureRmPipeline-conn'
    subscriptionId: '5db2748c-0da5-4e68-b618-b7f8564403e6'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'AzureRmPipeline-RG'
    location: 'Central US'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/cloudysingh/AzureRmPipeline-repo/main/azuredeploy.json'
    overrideParameters: '-projectName jgao0214'
    deploymentMode: 'Incremental'
    deploymentName: 'DeploymentPipelineTemplate'
- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
